'use client'
// import type { Metadata } from "next";
import HomeScreenHeader from "@/components/HomeScreenHeader";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{height: "100vh", width: "100%"}}>
      <body
          style={{
              height: "100%",
              width: "100%",
              overflow: "hidden",
              backgroundColor: '#5c5959',
              backgroundImage: "radial-gradient(farthest-corner at 30% 60%, rgba(63,94,251,1) 0%, rgba(177,12,186,0.7959558823529411) 10%, rgba(207,47,127,1) 20%, rgba(0,0,0,1) 50%", }}>
        {HomeScreenHeader()}
        {children}
      </body>
    </html>
  );
}
